[package]
name = "d"
version = "0.1.0"
authors = ["lightning1141 <lightning1141@gmail.com>"]

[dependencies]
log = "0.3"
log4rs = "0.7"
env_logger = "0.4"
clap = "2.26"
reqwest = "0.7"
error-chain = "0.11.0"
regex = "0.2"
